const fs = require('fs-extra');
const path = require('path');

const WORKSPACE_ROOT = path.resolve(__dirname, '../../../');
const APPS_DIR = path.join(WORKSPACE_ROOT, 'apps');

async function improveReadmes() {
    console.log('Starting README improvement...');

    try {
        const dirs = await fs.readdir(APPS_DIR);

        for (const dir of dirs) {
            const projectPath = path.join(APPS_DIR, dir);
            const stats = await fs.stat(projectPath);

            if (stats.isDirectory()) {
                const packageJsonPath = path.join(projectPath, 'package.json');
                if (await fs.pathExists(packageJsonPath)) {
                    const pkg = await fs.readJson(packageJsonPath);
                    console.log(`Processing ${pkg.name}...`);

                    const readmeContent = generateReadme(pkg.name, pkg.description);
                    await fs.writeFile(path.join(projectPath, 'README.md'), readmeContent);
                }
            }
        }
        console.log('All READMEs updated.');

    } catch (e) {
        console.error('Error improving READMEs:', e);
    }
}

function generateReadme(name, description) {
    const formattedName = name.split('-').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' ');

    return `# ${formattedName}

![Active Status](https://img.shields.io/badge/Status-Active-brightgreen)
![Last Commit](https://img.shields.io/badge/Maintained%3F-yes-green.svg)

**${description || 'A cutting-edge technology project.'}**

## 🚀 About The Project
This project is part of a high-frequency automated portfolio exploring the intersection of **Stock Markets** and **Technology**. It is designed to run autonomously, updating its own data and logic daily.

## ✨ Key Features
- **Automated daily updates**: Runs 4x a day to fetch new data or optimize logic.
- **Self-healing**: Includes scripts to verify its own integrity.
- **Modular Architecture**: Built to be easily enhanced by the Master Enhancer system.

## 🛠️ Getting Started

### Prerequisites
- Node.js (v18+)

### Installation
\`\`\`bash
npm install
\`\`\`

### Usage
\`\`\`bash
npm start
\`\`\`

## 🤖 Daily Automation
This project is enhancing itself daily via GitHub Actions.
- **Data Refresh**: 00:00, 06:00, 12:00, 18:00 UTC
- **Code Optimization**: Randomly triggered by the factory.

---
*Generated by Project Factory Automation*
`;
}

improveReadmes();
